### ISSUE TITLE
Styling Multiple Elements

### ISSUE THREAD

**Issue by cyouh95** [aboseman1/Cozy#2]
Instead of creating separate `class`es for each of the 3 locations [here](https://github.com/aboseman1/Cozy/blob/master/index.html#L72-L91) (ie. `box1`, `box2`, `box3`), you can use the same class for all 3 (ie. `box`). That way, you could avoid [repetition in your stylesheet](https://github.com/aboseman1/Cozy/blob/master/css/style.css#L159-L172):

```css
 .box {
   background-color: black;
   width: 300px;
 }
```
